
modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
#issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="earthspawn"
version="1.16.5-0.0.1"
displayName="Earthspawn"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/Earthspawn/earthspawn_mod"
logoFile="earthspawn_logo.png"
credits="Made with GitHub and Forge MDK"
authors="Chipser, Xscreade"
description='''An adventure and exploration for Minecraft,
Adding bosses, biomes and more cool features!'''

[[dependencies.earthspawn]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.earthspawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
